import fs from 'fs/promises'
import path from 'path'
import { promisify } from 'util'
import chalk from 'chalk'
import ncp from 'ncp'
import execa from 'execa'
import Listr from 'listr'
import { projectInstall } from 'pkg-install'